### ISSUE TITLE
Spazmalqon yoxdu

### ISSUE THREAD

**Issue by AfganAbbas** [fuadslymnv/Course-work-pharmacy-website#1]
Dermanlar arasinda spazmalqon yoxdu, basim agriyir tecili elave olunsun

**Comment by fuadslymnv** [comment]
Şikayətiniz üçün təşəkkür edirik.Yaxın zamanda gətirələcək.

**Comment by fuadslymnv** [comment]
> Dermanlar arasinda spazmalqon yoxdu, basim agriyir tecili elave olunsun

Şikayətiniz üçün təşəkkür edirik.Yaxın zamanda gətiriləcək.

**Comment by TofuJoseph** [comment]
![6439_2](https://github.com/fuadslymnv/Course-work-pharmacy-website/assets/126610603/0b644ce3-4c2f-4f7a-9e25-024da72f1220)

**Comment by TofuJoseph** [comment]
![Screenshot 2023-05-19 211002](https://github.com/fuadslymnv/Course-work-pharmacy-website/assets/126610603/ec24039d-c1a1-4c3d-8105-fc8af931fb75)

**Comment by fuadslymnv** [comment]
> ![Screenshot 2023-05-19 211002](https://github.com/fuadslymnv/Course-work-pharmacy-website/assets/126610603/ec24039d-c1a1-4c3d-8105-fc8af931fb75)
> 
> 

Bu uje ölkeye getirilmir

**Comment by TofuJoseph** [comment]
SJAKAJFİE İUÜGÜUİHGÜAG
